Repository edgexfoundry/developer-scripts, pull requests merged in 2020-02, with the labels that each got.

#217 feat[security-services]: Reduce exposure of sensitive assets
  releases/nightly-build/compose-files/docker-compose-nexus-arm64.yml
  releases/nightly-build/compose-files/docker-compose-nexus.yml
Labels: enhancement, geneva

#218 Initial Docker Compose files with for Redis default
  releases/nightly-build/compose-files/docker-compose-nexus-mongo-no-secty-arm64.yml
  releases/nightly-build/compose-files/docker-compose-nexus-mongo-no-secty.yml
  releases/nightly-build/compose-files/docker-compose-nexus-redis-no-secty-arm64.yml
  releases/nightly-build/compose-files/docker-compose-nexus-redis-no-secty.yml
Labels: geneva

#204 Bump version of postgres container (to 12.1-apline)
  releases/nightly-build/compose-files/docker-compose-nexus-arm64.yml
  releases/nightly-build/compose-files/docker-compose-nexus.yml
Labels: geneva, security_audit

#219 Fix postgres-db initialization requires a password to start now
  releases/fuji/compose-files/docker-compose-fuji.yml
  releases/nightly-build/compose-files/docker-compose-nexus-arm64.yml
  releases/nightly-build/compose-files/docker-compose-nexus.yml
Labels: geneva, security_audit

#203 (feat)[security-services] Update Kong version to 2.0.1
  releases/nightly-build/compose-files/docker-compose-nexus-arm64.yml
  releases/nightly-build/compose-files/docker-compose-nexus.yml
Labels: geneva, security_audit

#227 fix[security-services]: Address race condition for mongodb initialization
  releases/nightly-build/compose-files/docker-compose-nexus-mongo-arm64.yml
  releases/nightly-build/compose-files/docker-compose-nexus-mongo.yml
Labels: bug, on-hold
