Repository edgexfoundry/developer-scripts, pull requests merged in 2020-01, with the labels that each got.

#205 Allocate a tty to kong
  releases/nightly-build/compose-files/docker-compose-nexus-arm64.yml
  releases/nightly-build/compose-files/docker-compose-nexus.yml
Labels: bug, geneva

#206 Use security version of docker-edgex-consul for arm64.
  releases/nightly-build/compose-files/docker-compose-nexus-arm64.yml
Labels: bug, geneva

#201 Version bump of Vault container (to 1.3.1)
  releases/nightly-build/compose-files/docker-compose-nexus-arm64.yml
  releases/nightly-build/compose-files/docker-compose-nexus.yml
Labels: geneva, security_audit

#211 Enable edgex-proxy to use per-service token instead of root token.
  releases/nightly-build/compose-files/docker-compose-nexus-arm64.yml
  releases/nightly-build/compose-files/docker-compose-nexus.yml
Labels: enhancement, geneva

#200 Update device services' image version number
  releases/fuji/compose-files/docker-compose-fuji-no-secty.yml
  releases/fuji/compose-files/docker-compose-fuji.yml
  releases/fuji/compose-files/docker-compose-redis-fuji-no-secty.yml
Labels: fuji

#214 Fix vault-worker on arm64 security build so that it mounts all secrets volumes
  releases/nightly-build/compose-files/docker-compose-nexus-arm64.yml
Labels: bug, geneva

#216 Expose non-root Vault tokens to services currently needing root token.
  releases/nightly-build/compose-files/docker-compose-nexus-arm64.yml
  releases/nightly-build/compose-files/docker-compose-nexus.yml
Labels: enhancement, geneva
