Repository edgexfoundry/developer-scripts, pull requests merged in 2020-10, with the labels that each got.

#322 fix(makefile): make gen dev to generate the matched docker core service images versioning
  releases/nightly-build/compose-files/source/Makefile
  releases/nightly-build/compose-files/source/README.md
Labels: 2-medium, bug

#323 build(all): add supporting files for conventional commits
  .github/Contributing.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/semantic.yml
Labels: ci, hanoi

#324 ci: init Jenkins smoke test pipeline
  Jenkinsfile
Labels: ci, enhancement, hanoi

#328 fix: replace broken link in pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: bug, documentation, hanoi
